version: '3.8'
services:
  rag:
    build: ./RAG
    ports:
      - "8002:8002"
    env_file:
      - .env
    working_dir: /app

  ingestion:
    build: ./Ingestion_pipeline
    ports:
      - "8000:8000"
    env_file:
      - .env
    working_dir: /app

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - rag
      - ingestion

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend 